//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sGridServer.Resources.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationMailer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMailer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sGridServer.Code.Utilities.Resources.NotificationMailer", typeof(NotificationMailer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You unlocked a sGrid achievement.
        /// </summary>
        internal static string AchievementUnlockedHeader {
            get {
                return ResourceManager.GetString("AchievementUnlockedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, 
        ///
        ///You have unlocked the &quot;{1}&quot; achievement.
        ///
        ///Congratulations,
        ///your sGrid Team.
        /// </summary>
        internal static string AchievementUnlockedMail {
            get {
                return ResourceManager.GetString("AchievementUnlockedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, 
        ///
        ///{1} coins have been added to your coin account. 
        ///Your current account balance is now {2} coins. 
        ///
        ///Have fun,
        ///your sGrid Team.
        /// </summary>
        internal static string CoinTransactionDestinationMail {
            get {
                return ResourceManager.GetString("CoinTransactionDestinationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sGrid account balance has changed.
        /// </summary>
        internal static string CoinTransactionHeader {
            get {
                return ResourceManager.GetString("CoinTransactionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, 
        ///
        ///{1} coins have been spent from your coin account.  
        ///Your current account balance is now {2} coins. 
        ///
        ///Have fun,
        ///your sGrid Team.
        /// </summary>
        internal static string CoinTransactionSourceMail {
            get {
                return ResourceManager.GetString("CoinTransactionSourceMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sGrid project has been changed.
        /// </summary>
        internal static string ProjectChangedHeader {
            get {
                return ResourceManager.GetString("ProjectChangedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, 
        ///
        ///Your project has successfully been changed to {1}. 
        ///
        ///Have fun,
        ///your sGrid Team.
        /// </summary>
        internal static string ProjectChangedMail {
            get {
                return ResourceManager.GetString("ProjectChangedMail", resourceCulture);
            }
        }
    }
}
