//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sGridServer.Resources.Frontpage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Frontpage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frontpage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sGridServer.Views.Shared.Resources.Frontpage", typeof(Frontpage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore....
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/buttons/ExploreFrontpage.png.
        /// </summary>
        public static string ExploreImage {
            get {
                return ResourceManager.GetString("ExploreImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your reward.
        /// </summary>
        public static string GetReward {
            get {
                return ResourceManager.GetString("GetReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volunteered time will be immediately credited to You. Then You can exchange the grant for various rewards..
        /// </summary>
        public static string GetRewardText {
            get {
                return ResourceManager.GetString("GetRewardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join!.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/buttons/JoinFrontpage.png.
        /// </summary>
        public static string JoinImage {
            get {
                return ResourceManager.GetString("JoinImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed up science.
        /// </summary>
        public static string Speedup {
            get {
                return ResourceManager.GetString("Speedup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sGrid makes it possible to share currently not needed resources with charitable projects..
        /// </summary>
        public static string SpeedUpText {
            get {
                return ResourceManager.GetString("SpeedUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sGrid provides a new way to use surplus IT-resources by enabling volunteers to participate in distributed computing for charitable projects in an easy and intuitive way..
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
