//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sGrid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sGrid.Resources.ClientRes", typeof(ClientRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Performance.
        /// </summary>
        internal static string AllowedPerformance {
            get {
                return ResourceManager.GetString("AllowedPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Space.
        /// </summary>
        internal static string AllowedSpace {
            get {
                return ResourceManager.GetString("AllowedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        internal static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Boinc installation has been detected. sGrid will quit now.
        ///
        ///If you want to use sGrid, uninstall Boinc and remove the registry keys &quot;HKEY_LOCAL_MACHINE\SOFTWARE\Space Sciences Laboratory, U.C. Berkeley\BOINC Setup&quot; and &quot;HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Space Sciences Laboratory, U.C. Berkeley\BOINC Setup&quot;..
        /// </summary>
        internal static string BoincAlreadyInstalled {
            get {
                return ResourceManager.GetString("BoincAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to BOINC could not be established. Do you want to retry to connect to BOINC?
        ///Otherwise the application will be closed..
        /// </summary>
        internal static string BoincNotStarted {
            get {
                return ResourceManager.GetString("BoincNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using your Graphics Processing Unit may have a noticeable impact on the speed of your display..
        /// </summary>
        internal static string GPUWarning {
            get {
                return ResourceManager.GetString("GPUWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you log out your current progress will be lost.
        ///
        ///Do you still wish to log out?.
        /// </summary>
        internal static string LogOutWarning {
            get {
                return ResourceManager.GetString("LogOutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client needs new work, but is not online.
        ///Please connect to the internet to continue calculating..
        /// </summary>
        internal static string NoConnectionWarning {
            get {
                return ResourceManager.GetString("NoConnectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to choose a project to be able to calculate for science.
        ///Go to {0} to do so..
        /// </summary>
        internal static string NoProjectWarning {
            get {
                return ResourceManager.GetString("NoProjectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an old version of the client.
        ///Please fetch a new one..
        /// </summary>
        internal static string OldResourceWarning {
            get {
                return ResourceManager.GetString("OldResourceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin with work automatically when the computer starts.
        /// </summary>
        internal static string OptionAutostart {
            get {
                return ResourceManager.GetString("OptionAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do work when my computer is on Energy-Saver mode.
        /// </summary>
        internal static string OptionEnergySaver {
            get {
                return ResourceManager.GetString("OptionEnergySaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the graphics card to accelerate the calculation.
        /// </summary>
        internal static string OptionGraphicsCard {
            get {
                return ResourceManager.GetString("OptionGraphicsCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do work when my computer runs on battery.
        /// </summary>
        internal static string OptionOnBattery {
            get {
                return ResourceManager.GetString("OptionOnBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current performance setting is high! This will speed up the computation of work!.
        /// </summary>
        internal static string PerformanceSetHigh {
            get {
                return ResourceManager.GetString("PerformanceSetHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current performance setting is low. This can slow down the computation of work..
        /// </summary>
        internal static string PerformanceSetLow {
            get {
                return ResourceManager.GetString("PerformanceSetLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current performance setting is fine!.
        /// </summary>
        internal static string PerformanceSetMiddle {
            get {
                return ResourceManager.GetString("PerformanceSetMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sGrid Client with {0}.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sGrid Client.
        /// </summary>
        internal static string ProjectNameUnknown {
            get {
                return ResourceManager.GetString("ProjectNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sGrid.
        /// </summary>
        internal static string sGrid {
            get {
                return ResourceManager.GetString("sGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current space setting is high! This will speed up the computation of work!.
        /// </summary>
        internal static string SpaceSetHigh {
            get {
                return ResourceManager.GetString("SpaceSetHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current space setting is low. This can slow down the computation of work..
        /// </summary>
        internal static string SpaceSetLow {
            get {
                return ResourceManager.GetString("SpaceSetLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current space setting is fine!.
        /// </summary>
        internal static string SpaceSetMiddle {
            get {
                return ResourceManager.GetString("SpaceSetMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations are running.
        ///Remaining time: {0}..
        /// </summary>
        internal static string StatusRemainingTime {
            get {
                return ResourceManager.GetString("StatusRemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching new work
        ///from server.
        /// </summary>
        internal static string WorkFetching {
            get {
                return ResourceManager.GetString("WorkFetching", resourceCulture);
            }
        }
    }
}
