//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MemberStatsWithTeamHistory {
    
    private string teamHistoryField;
    
    private MemberStatsWithTeamHistoryMemberStats[] memberStatsField;
    
    private MemberStatsWithTeamHistoryMemberStatsByProjects[] memberStatsByProjectsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TeamHistory {
        get {
            return this.teamHistoryField;
        }
        set {
            this.teamHistoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MemberStats", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MemberStatsWithTeamHistoryMemberStats[] MemberStats {
        get {
            return this.memberStatsField;
        }
        set {
            this.memberStatsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MemberStatsByProjects", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MemberStatsWithTeamHistoryMemberStatsByProjects[] MemberStatsByProjects {
        get {
            return this.memberStatsByProjectsField;
        }
        set {
            this.memberStatsByProjectsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MemberStatsWithTeamHistoryMemberStats {
    
    private MemberStatsWithTeamHistoryMemberStatsMemberStat[] memberStatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MemberStat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MemberStatsWithTeamHistoryMemberStatsMemberStat[] MemberStat {
        get {
            return this.memberStatField;
        }
        set {
            this.memberStatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MemberStatsWithTeamHistoryMemberStatsMemberStat {
    
    private string nameField;
    
    private int memberIdField;
    
    private bool memberIdFieldSpecified;
    
    private System.DateTime registerDateField;
    
    private bool registerDateFieldSpecified;
    
    private System.DateTime lastResultField;
    
    private bool lastResultFieldSpecified;
    
    private int numDevicesField;
    
    private bool numDevicesFieldSpecified;
    
    private MemberStatsWithTeamHistoryMemberStatsMemberStatStatisticsTotals[] statisticsTotalsField;
    
    private MemberStatsWithTeamHistoryMemberStatsMemberStatStatisticsAverages[] statisticsAveragesField;
    
    private MemberStatsWithTeamHistoryMemberStatsMemberStatResource[] resourceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int MemberId {
        get {
            return this.memberIdField;
        }
        set {
            this.memberIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MemberIdSpecified {
        get {
            return this.memberIdFieldSpecified;
        }
        set {
            this.memberIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime RegisterDate {
        get {
            return this.registerDateField;
        }
        set {
            this.registerDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RegisterDateSpecified {
        get {
            return this.registerDateFieldSpecified;
        }
        set {
            this.registerDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime LastResult {
        get {
            return this.lastResultField;
        }
        set {
            this.lastResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LastResultSpecified {
        get {
            return this.lastResultFieldSpecified;
        }
        set {
            this.lastResultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int NumDevices {
        get {
            return this.numDevicesField;
        }
        set {
            this.numDevicesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumDevicesSpecified {
        get {
            return this.numDevicesFieldSpecified;
        }
        set {
            this.numDevicesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StatisticsTotals", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MemberStatsWithTeamHistoryMemberStatsMemberStatStatisticsTotals[] StatisticsTotals {
        get {
            return this.statisticsTotalsField;
        }
        set {
            this.statisticsTotalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StatisticsAverages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MemberStatsWithTeamHistoryMemberStatsMemberStatStatisticsAverages[] StatisticsAverages {
        get {
            return this.statisticsAveragesField;
        }
        set {
            this.statisticsAveragesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Resource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MemberStatsWithTeamHistoryMemberStatsMemberStatResource[] Resource {
        get {
            return this.resourceField;
        }
        set {
            this.resourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MemberStatsWithTeamHistoryMemberStatsMemberStatStatisticsTotals {
    
    private int runTimeField;
    
    private bool runTimeFieldSpecified;
    
    private int runTimeRankField;
    
    private bool runTimeRankFieldSpecified;
    
    private int pointsField;
    
    private bool pointsFieldSpecified;
    
    private int pointsRankField;
    
    private bool pointsRankFieldSpecified;
    
    private int resultsField;
    
    private bool resultsFieldSpecified;
    
    private int resultsRankField;
    
    private bool resultsRankFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int RunTime {
        get {
            return this.runTimeField;
        }
        set {
            this.runTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RunTimeSpecified {
        get {
            return this.runTimeFieldSpecified;
        }
        set {
            this.runTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int RunTimeRank {
        get {
            return this.runTimeRankField;
        }
        set {
            this.runTimeRankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RunTimeRankSpecified {
        get {
            return this.runTimeRankFieldSpecified;
        }
        set {
            this.runTimeRankFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Points {
        get {
            return this.pointsField;
        }
        set {
            this.pointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PointsSpecified {
        get {
            return this.pointsFieldSpecified;
        }
        set {
            this.pointsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int PointsRank {
        get {
            return this.pointsRankField;
        }
        set {
            this.pointsRankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PointsRankSpecified {
        get {
            return this.pointsRankFieldSpecified;
        }
        set {
            this.pointsRankFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Results {
        get {
            return this.resultsField;
        }
        set {
            this.resultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResultsSpecified {
        get {
            return this.resultsFieldSpecified;
        }
        set {
            this.resultsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ResultsRank {
        get {
            return this.resultsRankField;
        }
        set {
            this.resultsRankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResultsRankSpecified {
        get {
            return this.resultsRankFieldSpecified;
        }
        set {
            this.resultsRankFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MemberStatsWithTeamHistoryMemberStatsMemberStatStatisticsAverages {
    
    private int runTimePerDayField;
    
    private bool runTimePerDayFieldSpecified;
    
    private int runTimePerResultField;
    
    private bool runTimePerResultFieldSpecified;
    
    private double pointsPerHourRunTimeField;
    
    private bool pointsPerHourRunTimeFieldSpecified;
    
    private double pointsPerDayField;
    
    private bool pointsPerDayFieldSpecified;
    
    private double pointsPerResultField;
    
    private bool pointsPerResultFieldSpecified;
    
    private double resultsPerDayField;
    
    private bool resultsPerDayFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int RunTimePerDay {
        get {
            return this.runTimePerDayField;
        }
        set {
            this.runTimePerDayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RunTimePerDaySpecified {
        get {
            return this.runTimePerDayFieldSpecified;
        }
        set {
            this.runTimePerDayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int RunTimePerResult {
        get {
            return this.runTimePerResultField;
        }
        set {
            this.runTimePerResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RunTimePerResultSpecified {
        get {
            return this.runTimePerResultFieldSpecified;
        }
        set {
            this.runTimePerResultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double PointsPerHourRunTime {
        get {
            return this.pointsPerHourRunTimeField;
        }
        set {
            this.pointsPerHourRunTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PointsPerHourRunTimeSpecified {
        get {
            return this.pointsPerHourRunTimeFieldSpecified;
        }
        set {
            this.pointsPerHourRunTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double PointsPerDay {
        get {
            return this.pointsPerDayField;
        }
        set {
            this.pointsPerDayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PointsPerDaySpecified {
        get {
            return this.pointsPerDayFieldSpecified;
        }
        set {
            this.pointsPerDayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double PointsPerResult {
        get {
            return this.pointsPerResultField;
        }
        set {
            this.pointsPerResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PointsPerResultSpecified {
        get {
            return this.pointsPerResultFieldSpecified;
        }
        set {
            this.pointsPerResultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double ResultsPerDay {
        get {
            return this.resultsPerDayField;
        }
        set {
            this.resultsPerDayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResultsPerDaySpecified {
        get {
            return this.resultsPerDayFieldSpecified;
        }
        set {
            this.resultsPerDayFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MemberStatsWithTeamHistoryMemberStatsMemberStatResource {
    
    private string urlField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MemberStatsWithTeamHistoryMemberStatsByProjects {
    
    private MemberStatsWithTeamHistoryMemberStatsByProjectsProject[] projectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Project", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MemberStatsWithTeamHistoryMemberStatsByProjectsProject[] Project {
        get {
            return this.projectField;
        }
        set {
            this.projectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MemberStatsWithTeamHistoryMemberStatsByProjectsProject {
    
    private string projectNameField;
    
    private string projectShortNameField;
    
    private int runTimeField;
    
    private bool runTimeFieldSpecified;
    
    private int pointsField;
    
    private bool pointsFieldSpecified;
    
    private int resultsField;
    
    private bool resultsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProjectName {
        get {
            return this.projectNameField;
        }
        set {
            this.projectNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProjectShortName {
        get {
            return this.projectShortNameField;
        }
        set {
            this.projectShortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int RunTime {
        get {
            return this.runTimeField;
        }
        set {
            this.runTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RunTimeSpecified {
        get {
            return this.runTimeFieldSpecified;
        }
        set {
            this.runTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Points {
        get {
            return this.pointsField;
        }
        set {
            this.pointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PointsSpecified {
        get {
            return this.pointsFieldSpecified;
        }
        set {
            this.pointsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Results {
        get {
            return this.resultsField;
        }
        set {
            this.resultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResultsSpecified {
        get {
            return this.resultsFieldSpecified;
        }
        set {
            this.resultsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private MemberStatsWithTeamHistory[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MemberStatsWithTeamHistory")]
    public MemberStatsWithTeamHistory[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
