//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sGridServer.Resources.Support {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageOverview {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageOverview() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sGridServer.Views.Support.Resources.MessageOverview", typeof(MessageOverview).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        public static string AdminText {
            get {
                return ResourceManager.GetString("AdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllText {
            get {
                return ResourceManager.GetString("AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Partners.
        /// </summary>
        public static string CoinPartnerText {
            get {
                return ResourceManager.GetString("CoinPartnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registred Users.
        /// </summary>
        public static string RegistredUserText {
            get {
                return ResourceManager.GetString("RegistredUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resolved only.
        /// </summary>
        public static string ResolvedText {
            get {
                return ResourceManager.GetString("ResolvedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string SponsorText {
            get {
                return ResourceManager.GetString("SponsorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unregistred Users.
        /// </summary>
        public static string UnregistredUserText {
            get {
                return ResourceManager.GetString("UnregistredUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unresolved only.
        /// </summary>
        public static string UnresolvedText {
            get {
                return ResourceManager.GetString("UnresolvedText", resourceCulture);
            }
        }
    }
}
