//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sGridServer.Resources.IdProviders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EMailIdProvider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EMailIdProvider() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sGridServer.Controllers.Resources.EMailIdProvider", typeof(EMailIdProvider).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered text did not match the given image. Please retry..
        /// </summary>
        internal static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given e-mail address is already in use by another user. .
        /// </summary>
        internal static string EMailAlreadyInUse {
            get {
                return ResourceManager.GetString("EMailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we did not find the e-mail address you entered..
        /// </summary>
        internal static string EMailNotFound {
            get {
                return ResourceManager.GetString("EMailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given account is not valid for this login method. Did you use an open id provider like Facebook when registering yourself?.
        /// </summary>
        internal static string InvalidIdType {
            get {
                return ResourceManager.GetString("InvalidIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password was incorrect..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given answer was not valid. .
        /// </summary>
        internal static string InvalidSecurityAnswer {
            get {
                return ResourceManager.GetString("InvalidSecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered user has not been found. .
        /// </summary>
        internal static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password confirmation does not match the entered password. .
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0},
        ///
        ///We received a request to recover your password. To do so, please click on the following link:
        ///
        ///{1}
        ///
        ///If you did not make this request, please report the issue to us.
        ///
        /// Your sGrid Team.
        /// </summary>
        internal static string RecoveryEMailBody {
            get {
                return ResourceManager.GetString("RecoveryEMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sGrid password recovery.
        /// </summary>
        internal static string RecoveryEMailSubject {
            get {
                return ResourceManager.GetString("RecoveryEMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given username is already in use by another user. .
        /// </summary>
        internal static string UsernameAlreadyInUse {
            get {
                return ResourceManager.GetString("UsernameAlreadyInUse", resourceCulture);
            }
        }
    }
}
