//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sGridServer.Resources.Friends {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Friends {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Friends() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sGridServer.Controllers.Resources.Friends", typeof(Friends).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,
        ///
        ///Your friend {0} has invited you to sGrid! Click on the on the following link to join us:
        ///
        ///{1}
        ///
        ///Your sGrid Team.
        /// </summary>
        internal static string InviteEmailBody {
            get {
                return ResourceManager.GetString("InviteEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You was invited to sGrid!.
        /// </summary>
        internal static string InviteEmailSubject {
            get {
                return ResourceManager.GetString("InviteEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no friends yet..
        /// </summary>
        internal static string NoFriends {
            get {
                return ResourceManager.GetString("NoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no new friendship requests..
        /// </summary>
        internal static string NoRequests {
            get {
                return ResourceManager.GetString("NoRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It wasn&apos;t an e-mail address! Please, try again..
        /// </summary>
        internal static string WrongEmailToInvite {
            get {
                return ResourceManager.GetString("WrongEmailToInvite", resourceCulture);
            }
        }
    }
}
