//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sGridServer.Resources.MasterPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sGridServer.Controllers.Resources.MenuText", typeof(MenuText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string AchievementConfiguration {
            get {
                return ResourceManager.GetString("AchievementConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banners.
        /// </summary>
        internal static string BannerRequests {
            get {
                return ResourceManager.GetString("BannerRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string CoinExchange {
            get {
                return ResourceManager.GetString("CoinExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string ErrorLog {
            get {
                return ResourceManager.GetString("ErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string GridProjects {
            get {
                return ResourceManager.GetString("GridProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        internal static string Impressum {
            get {
                return ResourceManager.GetString("Impressum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string MessageRequests {
            get {
                return ResourceManager.GetString("MessageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsConfiguration {
            get {
                return ResourceManager.GetString("NewsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string PartnerDashboard {
            get {
                return ResourceManager.GetString("PartnerDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartnerFAQ.
        /// </summary>
        internal static string PartnerFAQ {
            get {
                return ResourceManager.GetString("PartnerFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string PartnerHelp {
            get {
                return ResourceManager.GetString("PartnerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string ProfileOverview {
            get {
                return ResourceManager.GetString("ProfileOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        internal static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        internal static string Rewards {
            get {
                return ResourceManager.GetString("Rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string SponsorDashboard {
            get {
                return ResourceManager.GetString("SponsorDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SponsorHelp {
            get {
                return ResourceManager.GetString("SponsorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string UserAchievement {
            get {
                return ResourceManager.GetString("UserAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string UserDashboard {
            get {
                return ResourceManager.GetString("UserDashboard", resourceCulture);
            }
        }
    }
}
