//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sGridServer.Resources.Achievements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AchievementRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AchievementRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sGridServer.Views.Achievement.Resources.AchievementRes", typeof(AchievementRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account balance.
        /// </summary>
        public static string AccountBalance {
            get {
                return ResourceManager.GetString("AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active time in days.
        /// </summary>
        public static string ActiveTime {
            get {
                return ResourceManager.GetString("ActiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount of coins.
        /// </summary>
        public static string AmountOfCoins {
            get {
                return ResourceManager.GetString("AmountOfCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bonus coins.
        /// </summary>
        public static string BonucCoins {
            get {
                return ResourceManager.GetString("BonucCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of times to send the fast answer in.
        /// </summary>
        public static string CountOfFastCalculations {
            get {
                return ResourceManager.GetString("CountOfFastCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current image.
        /// </summary>
        public static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the following form..
        /// </summary>
        public static string FormHello {
            get {
                return ResourceManager.GetString("FormHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value named &quot;{0}&quot; has to be nonnegative..
        /// </summary>
        public static string HasToBeNonnegative {
            get {
                return ResourceManager.GetString("HasToBeNonnegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value named &quot;{0}&quot; has to be positive..
        /// </summary>
        public static string HasToBePositive {
            get {
                return ResourceManager.GetString("HasToBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimal highscore placement.
        /// </summary>
        public static string HighscorePlacement {
            get {
                return ResourceManager.GetString("HighscorePlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: An identical achievement has already been created..
        /// </summary>
        public static string IdentityError {
            get {
                return ResourceManager.GetString("IdentityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to considered timespan in days.
        /// </summary>
        public static string MinimalLimit {
            get {
                return ResourceManager.GetString("MinimalLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new image.
        /// </summary>
        public static string NewImage {
            get {
                return ResourceManager.GetString("NewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of achievements.
        /// </summary>
        public static string NumberOfAchievements {
            get {
                return ResourceManager.GetString("NumberOfAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of clients.
        /// </summary>
        public static string NumberOfClients {
            get {
                return ResourceManager.GetString("NumberOfClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of friends.
        /// </summary>
        public static string NumberOfFriends {
            get {
                return ResourceManager.GetString("NumberOfFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of packages.
        /// </summary>
        public static string NumberOfPackages {
            get {
                return ResourceManager.GetString("NumberOfPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of rewards.
        /// </summary>
        public static string NumberOfRewards {
            get {
                return ResourceManager.GetString("NumberOfRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coin partner id.
        /// </summary>
        public static string PartnerId {
            get {
                return ResourceManager.GetString("PartnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project short name.
        /// </summary>
        public static string ProjectShortName {
            get {
                return ResourceManager.GetString("ProjectShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid property labeled &quot;{0}&quot;..
        /// </summary>
        public static string PropertyError {
            get {
                return ResourceManager.GetString("PropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time of shopping in minutes.
        /// </summary>
        public static string TimeOfShopping {
            get {
                return ResourceManager.GetString("TimeOfShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement Creation Form.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no partner with such an id..
        /// </summary>
        public static string WrongPartnerIdError {
            get {
                return ResourceManager.GetString("WrongPartnerIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project you entered does not exist..
        /// </summary>
        public static string WrongProjectError {
            get {
                return ResourceManager.GetString("WrongProjectError", resourceCulture);
            }
        }
    }
}
